# Generated by Django 4.2.7 on 2023-11-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20190125_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
